fixed pre-push error that occures because py/python3 differences between unix and windows

diff --git a/.git_hooks/pre-push b/.git_hooks/pre-push
--- a/.git_hooks/pre-push
+++ b/.git_hooks/pre-push
@@ -4,27 +4,28 @@
 # this file has been modified from the original version
 
 echo 'Running tests'
-echo 'If you are running on a UNIX machine, ignore the " py: command not found" error'
 CHANGED=$(git diff-index --name-only HEAD --)
+HAS_PY=$(command -v py)
 
 if [ -n "$CHANGED" ]; then
   git stash >/dev/null
 fi
 
-py -m test.test_main
+if [ -n "$HAS_PY" ]; then
+  py -m test.test_main
+else
+  python3 -m test.test_main
+fi
+
 # shellcheck disable=SC2181
 if [ $? -ne 0 ]; then
-  python3 -m test.test_main
-  # shellcheck disable=SC2181
-  if [ $? -ne 0 ]; then
-    echo 'Aborting push (Attempting to push a repository where the test suite fails)'
-    echo 'If you are running on Windows and it says "python3: Permission denied", try installing python3 from the Mircosort Store'
-    echo 'Bypass with git push --no-verify'
-    if [ -n "$CHANGED" ]; then
-      git stash pop >/dev/null
-    fi
-    exit 1
+  echo 'Aborting push (Attempting to push a repository where the test suite fails)'
+  echo 'If you are running on Windows and it says "python3: Permission denied", try installing python3 from the Mircosort Store'
+  echo 'Bypass with git push --no-verify'
+  if [ -n "$CHANGED" ]; then
+    git stash pop >/dev/null
   fi
+  exit 1
 fi
 
 if [ -n "$CHANGED" ]; then
